language: python

install:
  - pip install codecov
  - pip install slackclient

script:
  - coverage run tests.py

after_success:
  - codecov --token=f81cc35a-5747-4103-b4c2-8b2484d24714

deploy:
  provider: s3
  access_key_id: AKIAJOFY74EJZE4MALFQ
  secret_access_key:
    secure: $AWS
  bucket: durango-part2
  endpoint: http://durango-part2.s3-website.us-east-2.amazonaws.com
  local-dir: build
  region: us-east-2
  skip_cleanup: true
  on:
    branch: num2
